proyectoDAPW/eventos/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\EventoController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('inicio');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');


Route::resource('eventos', EventoController::class);

Route::get('/eventoscomprar', [EventoController::class, 'comprar'])->name('eventos.comprar')->middleware('auth');

Route::post('/eventoscomprar', [EventoController::class, 'comprarStore'])->name('eventos.comprarstore')->middleware('auth');
Route::get('/misentradas', [EventoController::class, 'misentradas'])->name('eventos.misentradas')->middleware('auth');
Route::get('/infoentrada/{entrada}', [EventoController::class, 'infoentrada'])->name('eventos.infoentrada')->middleware('auth');

proyectoDAPW/eventos/resources/views/plantillas/master.blade.php
<!doctype html>
<html lang="es">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Clase DWCS - 2021-2022">
    <meta name="generator" content="">
    <title>@yield('title')</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/navbar-fixed/">

    <!-- Bootstrap core CSS -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet" />

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.1/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/5.1/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/5.1/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
    <link rel="icon" href="/docs/5.1/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#7952b3">
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        body {
            min-height: 75rem;
            padding-top: 4.5rem;
        }
    </style>
</head>

<body>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">EVENTALIA</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ route('inicio') }}">Inicio</a>
                    </li>
                    @auth
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('eventos.index') }}">Listado Eventos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('eventos.create') }}">Alta Eventos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('eventos.comprar') }}">Comprar Entradas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('eventos.misentradas') }}">Ver Mis Entradas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#" onclick="event.preventDefault();document.getElementById('logout-form').submit();">Desconectar</a>
                    </li>
                    @endauth
                    @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('register') }}">Registrarse</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">Login</a>
                    </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <main class="container-fluid">
        <div class="bg-light p-5 rounded">
            @yield('central')
        </div>
    </main>

    <form method="POST" id="logout-form" action="{{ route('logout') }}">
        @csrf
    </form>

    <script src="{{ asset('js/app.js') }}"></script>
</body>

</html>