proyectoDAPW/eventos/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\EventoController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('inicio');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');


Route::resource('eventos', EventoController::class);

Route::get('/eventoscomprar', [EventoController::class, 'comprar'])->name('eventos.comprar')->middleware('auth');

Route::post('/eventoscomprar', [EventoController::class, 'comprarStore'])->name('eventos.comprarstore')->middleware('auth');
Route::get('/misentradas', [EventoController::class, 'misentradas'])->name('eventos.misentradas')->middleware('auth');
Route::get('/infoentrada/{entrada}', [EventoController::class, 'infoentrada'])->name('eventos.infoentrada')->middleware('auth');

proyectoDAPW/eventos/app/Models/Evento.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Evento extends Model
{
    use HasFactory;
    // eventos (id, titulo, telefono, direccion, cartel, latitud, longitud, fecha_inicio, fecha_fin)

    // Atributos que se pueden asignar de manera masiva.
    protected $fillable = array('titulo', 'telefono', 'direccion', 'cartel', 'latitud', 'longitud', 'fecha_inicio', 'fecha_fin');

    public function usuarios()
    {
        return $this->belongsToMany(User::class)->withPivot(['fecha_venta', 'fecha_evento', 'precio', 'asiento', 'codigoqrcontrol']);
    }
}

proyectoDAPW/eventos/app/Http/Controllers/EventoController.php
<?php

namespace App\Http\Controllers;

use PDF;
use auth;
use File;
use App\Models\Evento;
use App\Models\EventoUser;
use App\Mail\enviarEntrada;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Session;
use App\Http\Requests\StoreEventoRequest;
use App\Http\Requests\StoreEventoUserRequest;

class EventoController extends Controller
{
    public function __construct()
    {
        //$this->middleware('auth')->except('create');
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Conseguir todos los eventos.
        $eventos = Evento::paginate(5);
        return view('eventos.index')->with('eventos', $eventos);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('eventos.create')->with('evento', new Evento());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreEventoRequest $request)
    {
        $datosvalidados = $request->validated();
        $datosvalidados['cartel'] = 'cartel_defecto.jpg';

        // Almacenamos el archivo recibido en el servidor
        if ($request->file('cartel')) {
            $fichero = $request->file('cartel');
            $nuevonombre = time() . '_' . $fichero->getClientOriginalName();

            // Movemos el archivo al destino. public/carteles/xxxxxx.jpg
            //$fichero->move('carteles', $nuevonombre);

            // Filesystem como 'local'. Esta opcion almacena en /storage/app/carteles/nombre_al_azar.
            //$ruta = $request->cartel->store('carteles');

            // Filesystem como 'local'. Esta opcion almacena en /storage/app/public/carteles/nombre_al_azar.
            $ruta = $request->cartel->store('carteles', 'public');
            $datosvalidados['cartel'] = $ruta;
        }

        // Almacenamos en la base de datos
        Evento::create($datosvalidados);

        // Guarde un mensaje Flash.
        Session::flash('mensaje', 'Evento dado de alta correctamente.');
        Session::flash('alert-class', 'alert-success');

        return redirect()->route('eventos.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Evento $evento)
    {
        // Conseguimos la informacion del evento
        return view('eventos.cartel')->with('evento', $evento);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Evento $evento)
    {
        return view('eventos.edit')->with('evento', $evento);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreEventoRequest $request, Evento $evento)
    {
        // Actualizamos el evento.
        $evento->update($request->validated());

        // Guarde un mensaje Flash.
        Session::flash('mensaje', 'Evento actualizado correctamente.');
        Session::flash('alert-class', 'alert-success');

        // Redireccionamos al index.
        return redirect()->route('eventos.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Evento $evento)
    {
        // Borramos el registro.
        $evento->delete();

        // Guarde un mensaje Flash.
        Session::flash('mensaje', 'Evento borrado correctamente.');
        Session::flash('alert-class', 'alert-success');

        // Redireccionamos al index.
        return redirect()->route('eventos.index');
    }

    // Devuelve el formulario para comprar una entrada.
    public function comprar()
    {
        // Conseguimos la lista de eventos disponibles.
        $eventos = Evento::all();
        return view('eventos.comprar')->with('eventos', $eventos)->with('entrada', new EventoUser());
    }

    public function comprarStore(StoreEventoUserRequest $request)
    {
        // Datos validados
        $datos_validados = $request->validated();

        // El id del usuario  // auth()->user()
        $datos_validados['user_id'] = auth()->user()->id;

        // Generamos el codigo qrcontrol.
        // Hacemos un md5 de fecha actual del sistema + id usuario + id evento
        $datos_validados['codigoqrcontrol'] = md5(microtime() . $datos_validados['user_id'] . $datos_validados['evento_id']);

        // La fecha de venta sería la fecha del sistema.
        $datos_validados['fecha_venta'] = date("Y-m-d");

        // Almacenamos en la tabla y redireccionamos al index.
        $entrada = EventoUser::create($datos_validados);

        // Buscamos la información del evento para pasarla al PDF
        $evento = Evento::where('id', '=',  $entrada->evento_id)->first();

        // Generamos el pdf..
        $datos = [
            'evento' => $evento,
            'entrada' => $entrada
        ];

        // Para descargar el PDF...
        //$pdf = PDF::loadView('eventos.entradapdf', $datos);
        //return $pdf->download('entrada.pdf');

        // Para enviar por correo electrónico...
        // Me guardo el PDF que voy a generar, por que tengo que adjuntarlo al correo.
        $rutaFicheroEntradaPDF = 'storage/Eventalia_' . md5(time()) . '.pdf';
        // Genero el PDF y lo guardo en esa ruta con ese nombre.
        $pdf = PDF::loadView('eventos.entradapdf', $datos);
        $pdf->save($rutaFicheroEntradaPDF);

        // Enviamos por correo electrónico
        try {
            Mail::to(auth()->user()->email)->send(new enviarEntrada($rutaFicheroEntradaPDF));
        } catch (\Exception $e) {
            dd($e->getMessage());
        }
        // Borramos el fichero temporal de la entrada PDF.
        File::delete(public_path($rutaFicheroEntradaPDF));

        // Guarde un mensaje Flash.
        Session::flash('mensaje', 'Venta realizada correctamente. Consulte su buzón de correo.');
        Session::flash('alert-class', 'alert-success');

        return redirect()->route('eventos.index');
    }

    public function misentradas()
    {
        // Listado con mis entradas.
        // Obtenemos las entradas del usuario que está conectado auth()->user()->id;
        $entradas = EventoUser::where('user_id', auth()->user()->id)->orderBy('fecha_evento')->get();
        return view('eventos.misentradas')->with('entradas', $entradas);
    }

    public function infoentrada(EventoUser $entrada)
    {
        // Averiguamos el titulo del evento para mostrarlo en el detalle de la entrada.
        $evento = Evento::where("id", "=", $entrada->evento_id)->first();

        // Listado con mis entradas.
        // Obtenemos las entradas del usuario que está conectado auth()->user()->id;
        return view('eventos.entrada')->with('entrada', $entrada)->with('evento', $evento);
    }
}

proyectoDAPW/eventos/resources/views/eventos/_form.blade.php
@csrf
<div class="mb-3">
    <label for="titulo" class="form-label">Título Evento:</label>
    <input type="text" class="form-control" id="titulo" name="titulo" value="{{ old('titulo',$evento->titulo) }}" required maxlength="150">
    @error('titulo')
    <small class='alert alert-danger'>{{ $message }}</small>
    @enderror
</div>

<div class="mb-3">
    <label for="telefono" class="form-label">Teléfono:</label>
    <input type="text" class="form-control" id="telefono" name="telefono" value="{{ old('telefono',$evento->telefono) }}" maxlength="15">
    @error('telefono')
    <small class='alert alert-danger'>{{ $message }}</small>
    @enderror
</div>
<div class="mb-3">
    <label for="direccion" class="form-label">Dirección:</label>
    <input type="text" class="form-control" id="direccion" name="direccion" value="{{ old('direccion',$evento->direccion) }}" maxlength="15" required>
    @error('direccion')
    <small class='alert alert-danger'>{{ $message }}</small>
    @enderror
</div>
<div class="mb-3">
    <label for="cartel" class="form-label">Fotografía cartel:</label> <strong>{{ old('cartel',$evento->cartel) }}</strong>
    <input type="file" class="form-control" id="cartel" name="cartel" value="{{ old('cartel',$evento->cartel) }}" maxlength="100">
    @if ($errors->has('cartel'))
    <small class='alert alert-danger'>{{ $errors->first('cartel') }}</small>
    @endif
</div>
<div class="mb-3">
    <label for="latitud" class="form-label">Latitud:</label>
    <input type="text" class="form-control" id="latitud" name="latitud" value="{{ old('latitud',$evento->latitud) }}" maxlength="20">
    @error('latitud')
    <small class='alert alert-danger'>{{ $message }}</small>
    @enderror
</div>
<div class="mb-3">
    <label for="longitud" class="form-label">Longitud:</label>
    <input type="text" class="form-control" id="longitud" name="longitud" value="{{ old('longitud',$evento->longitud) }}" maxlength="20">
    @error('longitud')
    <small class='alert alert-danger'>{{ $message }}</small>
    @enderror
</div>
<div class="mb-3">
    <label for="fecha_inicio" class="form-label">Fecha Inicio:</label>
    <input type="date" class="form-control" id="fecha_inicio" name="fecha_inicio" value="{{ old('fecha_inicio',$evento->fecha_inicio) }}">
    @error('fecha_inicio')
    <small class='alert alert-danger'>{{ $message }}</small>
    @enderror
</div>
<div class="mb-3">
    <label for="fecha_fin" class="form-label">Fecha Fin:</label>
    <input type="date" class="form-control" id="fecha_fin" name="fecha_fin" value="{{ old('fecha_fin',$evento->fecha_fin) }}">
    @error('fecha_fin')
    <small class='alert alert-danger'>{{ $message }}</small>
    @enderror
</div>

proyectoDAPW/eventos/resources/views/eventos/_formcomprar.blade.php
@csrf
<div class="mb-3">
    <label for="titulo" class="form-label">Evento:</label>
    <select name="evento_id" class="form-control" id="evento_id">
        <option value="0">Seleccione un evento</option>
        @foreach ($eventos as $evento)
        <option value="{{ $evento->id }}">{{ $evento->titulo}}</option>
        @endforeach
    </select>
    @error('titulo')
    <small class='alert alert-danger'>{{ $message }}</small>
    @enderror
</div>

<div class="mb-3">
    <label for="fecha_evento" class="form-label">Seleccione fecha:</label>
    <input type="date" class="form-control" id="fecha_evento" name="fecha_evento" value="{{ old('fecha_evento',$entrada->fecha_evento) }}">
    @error('fecha_evento')
    <small class='alert alert-danger'>{{ $message }}</small>
    @enderror
</div>
<div class="mb-3">
    <label for="precio" class="form-label">Precio:</label>
    <input type="number" class="form-control" id="precio" name="precio" value="{{ old('precio',$entrada->precio) }}" maxlength="15" required>
    @error('precio')
    <small class='alert alert-danger'>{{ $message }}</small>
    @enderror
</div>
<div class="mb-3">
    <label for="asiento" class="form-label">Asiento:</label>
    <input type="text" class="form-control" id="asiento" name="asiento" value="{{ old('asiento',$entrada->asiento) }}" maxlength="15">
    @error('asiento')
    <small class='alert alert-danger'>{{ $message }}</small>
    @enderror
</div>

proyectoDAPW/eventos/resources/views/eventos/cartel.blade.php
@extends('plantillas.master')

@section('title')
Información sobre Eventos
@stop

@section('central')
<h2>Información de Evento</h2>
<hr />
Titulo: {{ $evento->titulo }}<br />
Teléfono: {{ $evento->telefono }}<br />
Dirección: {{ $evento->direccion }}<br />
Fotografía del cartel: <img src='{{ URL::asset("storage/$evento->cartel") }}' width="320" /><br />
<hr />
Situación:
<iframe width="600" height="600" src="https://maps.google.com/maps?q={{ $evento->latitud }},{{ $evento->longitud }}&output=embed">
</iframe>
<br />
Fecha Inicio Evento: {{ \Carbon\Carbon::parse($evento->fecha_inicio)->format('d/m/Y') }}<br />
Fecha Fin Evento: {{ \Carbon\Carbon::parse($evento->fecha_fin)->format('d/m/Y') }}<br />
@stop

proyectoDAPW/eventos/resources/views/eventos/comprar.blade.php
@extends('plantillas.master')

@section('title')
Compra de Entradas
@stop

@section('central')
<h2>ALTA DE EVENTO</h2>
<form action="{{ route('eventos.comprarstore') }}" method="post">
    @include('eventos._formcomprar')
    <input type="reset" value="Limpiar" />
    <input type="submit" class="btn btn-primary" value="Comprar Entrada" />
</form>
@stop

proyectoDAPW/eventos/resources/views/eventos/create.blade.php
@extends('plantillas.master')

@section('title')
Alta de Eventos
@stop

@section('central')
<h2>ALTA DE EVENTO</h2>
<form action="{{ route('eventos.store') }}" method="post" enctype="multipart/form-data">
    @include('eventos._form')
    <input type="reset" name="Limpiar" />
    <input type="submit" class="btn btn-primary" name="Alta de Evento" />
</form>
@stop

proyectoDAPW/eventos/resources/views/eventos/edit.blade.php
@extends('plantillas.master')

@section('title')
Edición de Eventos
@stop

@section('central')
<h2>EDICIÓN DE EVENTO</h2>
<form action="{{ route('eventos.update',$evento->id) }}" method="post" enctype="multipart/form-data">
    @method('PUT')
    @include('eventos._form')
    <input type="reset" name="Limpiar" />
    <input type="submit" class="btn btn-primary" value="Actualizar Evento" />
</form>
@stop

proyectoDAPW/eventos/resources/views/eventos/entrada.blade.php
@extends('plantillas.master')

@section('title')
Detalles de la entrada
@stop

@section('central')
<h2>Entrada</h2>
<hr />
Evento: {{ $evento->titulo }}<br />
Foto: <img src='{{ URL::asset("storage/$evento->cartel") }}' width="320" /><br />
Fecha Venta: {{ \Carbon\Carbon::parse($entrada->fecha_venta)->format('d/m/Y') }}<br />
Fecha del Evento: {{ \Carbon\Carbon::parse($entrada->fecha_evento)->format('d/m/Y') }}<br />
Precio: {{ $entrada->precio }}<br />
Asiento: {{ $entrada->asiento }}<br />
<hr />
Codigo QR validación entrada: {!! QrCode::size(150)->generate($entrada->codigoqrcontrol) !!} <br />
<hr />
Código QR de Google Maps: {!! QrCode::size(150)->geo($evento->latitud, $evento->longitud) !!}
@stop

proyectoDAPW/eventos/resources/views/eventos/entradapdf.blade.php
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Entrada Eventalia</title>
</head>

<body>
    <center>
        SU ENTRADA EVENTALIA
        <H3>{{ $evento->titulo }}</H3>
    </center>
    <table>
        <tr valign="top" align="center">
            <td>
                <img src='{{ URL::asset("storage/$evento->cartel") }}' width="300" />
            </td>
            <td>
                <br /><br />
                <img src="data:image/png;base64, {!! base64_encode(QrCode::format('svg')->size(150)->generate($entrada->codigoqrcontrol)) !!} " />
                <h4>Muestre este código QR<br /> a la entrada del espectáculo</h4>
            </td>
        </tr>
    </table>
    <hr />
    <center>
        Fecha de Compra: {{ \Carbon\Carbon::parse($entrada->fecha_venta)->format('d/m/Y') }} || Fecha Evento: {{ \Carbon\Carbon::parse($entrada->fecha_evento)->format('d/m/Y') }}<br /><br />
        Precio: {{ $entrada->precio }}<br />
        Su Asiento: {{ $entrada->asiento }}<br />
        <h3>Localizacion del Evento</h3>
        <img src="data:image/png;base64, {!! base64_encode(QrCode::format('svg')->size(150)->geo($evento->latitud, $evento->longitud)) !!} ">
    </center>
</body>

</html>

proyectoDAPW/eventos/resources/views/eventos/index.blade.php
@extends('plantillas.master')

@section('title')
Listado de Eventos
@stop

@section('central')
<h2>LISTADO DE EVENTOS DISPONIBLES</h2>
<hr />
@if(Session::has('mensaje'))
<div class="alert {{ Session::get('alert-class') }}">
    {{ Session::get('mensaje') }}
</div>
@endif
<hr />
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Titulo</th>
            <th scope="col">Telefono</th>
            <th scope="col">Direccion</th>
            <th scope="col">Cartel</th>
            <th scope="col">Coordenadas</th>
            <th scope="col">Fecha Inicio</th>
            <th scope="col">Fecha Fin</th>
            <th scope="col">Edición</th>
        </tr>
    </thead>
    <tbody>
        @foreach($eventos as $evento)
        <tr>
            <th scope="row">{{ $evento->id }}</th>
            <th scope="row">{{ $evento->titulo }}</th>
            <th scope="row">{{ $evento->telefono }}</th>
            <th scope="row">{{ $evento->direccion }}</th>
            <th scope="row">{{ $evento->cartel }}</th>
            <th scope="row"><a href="http://maps.google.com/?ie=UTF8&hq=&ll={{ $evento->latitud }},{{ $evento->longitud }}&z=13" target="_blank">Google Maps</a></th>

            <th scope="row">{{ $evento->fecha_inicio }}</th>
            <th scope="row">{{ $evento->fecha_fin }}</th>
            <th scope="row"><a href="{{ route('eventos.edit',$evento) }}" class="btn btn-primary">Editar</a>
                <form action="{{ route('eventos.destroy',$evento) }}" method="post">@csrf @method('DELETE') <input type="submit" class="btn btn-primary" value="Borrar" /></form> <a href="{{ route('eventos.show',$evento) }}" class="btn btn-primary">Info</a>
            </th>
        </tr>
        @endforeach
    </tbody>
</table>

{!! $eventos->links() !!}

@stop

proyectoDAPW/eventos/resources/views/eventos/mailconentrada.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>This is test mail</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
    <div class="container text-center m-1">
        <h1 class="lead mt-3">Enhorabuena por su nueva entrada.</h1>
        <p class="lead">En este correo va un fichero adjunto que contiene el PDF de su entrada.</p>
        <p class="lead">Gracias por comprar en Eventalia</p>
    </div>
</body>

</html>

proyectoDAPW/eventos/resources/views/eventos/misentradas.blade.php
@extends('plantillas.master')

@section('title')
Mis entradas adquiridas
@stop

@section('central')
<h2>Entradas compradas</h2>
<hr />
<table class="table">
    <thead>
        <tr>
            <th scope="col">Evento_id</th>
            <th scope="col">Fecha Venta</th>
            <th scope="col">Fecha del Evento</th>
            <th scope="col">Precio</th>
            <th scope="col">Asiento</th>
            <th scope="col">Codigo QR</th>
            <th scope="col">Edición</th>
        </tr>
    </thead>
    <tbody>
        @foreach($entradas as $entrada)
        <tr>
            <th scope="row">{{ $entrada->evento_id }}</th>
            <th scope="row">{{ \Carbon\Carbon::parse($entrada->fecha_venta)->format('d/m/Y') }}</th>
            <th scope="row">{{ \Carbon\Carbon::parse($entrada->fecha_evento)->format('d/m/Y') }}</th>
            <th scope="row">{{ $entrada->precio }}</th>
            <th scope="row">{{ $entrada->asiento }}</th>
            <th scope="row">{{ $entrada->codigoqrcontrol }}</th>
            <th scope="row"><a href="{{ route('eventos.infoentrada',$entrada) }}" class="btn btn-primary">Más detalle</a>
            </th>
        </tr>
        @endforeach
    </tbody>
</table>
@stop